# Generated by Django 3.1.7 on 2021-03-21 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210319_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='group',
            new_name='groups',
        ),
    ]
